version: '3'
services:
  app:
    # network_mode: "host"
    image: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile 
    
    # command: "npm start"
    ports: 
      - '8800:8800'
    
    expose:
      - '8800'
    depends_on:
      - mongo
    
    networks:
      - internalnet
  mongo:
    image: mongo:4.4.6
    ports: 
      - '27017:27017'
    host: mongodb 
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge